services:
  postgres:
    image: postgres:16
    container_name: fraud_detection_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fraud_detection_db
      POSTGRES_USER: fraud_user
      POSTGRES_PASSWORD: fraud_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
